name: Build and Test Ubuntu latest gcc 11 x64

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize, converted_to_draft, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      OUTPUT_DIR: '/tmp/out'
    name: vt-tv
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Inspect Builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        id: docker_build
        continue-on-error: true
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: ./ci/ubuntu22.04-gcc11-x64.dockerfile
          tags: docker push pierrpebay/vt-tv:latest
          outputs: type=local,dest=${{ env.OUTPUT_DIR }}
      # - name: Upload Test Log Files
      #   uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: vt-tv-LastTestLogs
      #     path: ${{ env.OUTPUT_DIR }}
      # - name: Determine Job Failure or Success
      #   run: |
      #     echo "Success Flag with 0 pass and 1 fail:"
      #     cat ${{ env.OUTPUT_DIR }}/tmp/artifacts/success_flag.txt
      #     if [[  $(cat ${{ env.OUTPUT_DIR }}/tmp/artifacts/success_flag.txt) -eq 0 ]]; then exit 0; else exit 1; fi
      #   shell: bash
