name: Build and Test Bindings Ubuntu 22.04 gcc 11 x64

# Trigger the workflow on push or pull request
on:
  push:
   branches:
    - "*"
    #  - master
#  pull_request:
#    types: [opened, reopened, synchronize, converted_to_draft, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      OUTPUT_DIR: '/tmp/out'
    name: vt-tv bindings build and test
    steps:
      - uses: actions/checkout@v4

      - name: CI Variables
        id: vars
        run: echo "DOCKER_TAG=$(echo ${{ github.ref }} | cut -d'/' -f3- | sed 's/[^a-z0-9_-]/__/gi')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Inspect Builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
          echo "DOCKER_TAG: ${{ env.DOCKER_TAG }}"

      - name: Build the Docker Image; build and test vt-tv bindings
        id: docker_build
        uses: docker/build-push-action@v6 # from 5.3 error appears with some X11 file
        with:
          push: false
          tags: ${{ env.DOCKER_TAG }}
          context: .
          file: ./ci/build-and-test-bindings.dockerfile
          outputs: type=local,dest=${{ env.OUTPUT_DIR }}
          build-args: "--volume=\"/tmp/.X11-unix:/tmp/X11.unix:rw\""
