name: Build and Test

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - 97-add-more-environments-to-test-in-ci

jobs:
  build: 
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest ]
        vtk_version: [ 9.3.1 ]
        compiler: [ [gcc-12, g++-12, gcov-12] ]
    runs-on: ${{ matrix.os }}
    name: vt-tv build and test
    env:
        VTK_DIR: /opt/build/vtk
        SEGMENT_DOWNLOAD_TIMEOUT_MINS: 60
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install xquartz --cask

      - name: Set up environment
        run:
          export VTK_DIR=${{ env.VTK_DIR }}
          # export CC=${{ matrix.compiler[0] }}
          # export CXX=${{ matrix.compiler[1] }}
          # export GCOV=${{ matrix.compiler[2] }}

      - name: Set up cache
        id: vtk-cache
        uses: actions/cache@v3
        with:
          path: /opt/build/vtk
          key: ${{ matrix.os }}-vtk-build-${{ matrix.vtk_version }}

      - name: Build VTK
        id: cache-vtk-build
        if: ${{steps.vtk-cache.outputs.cache-hit != 'true'}}
        run: |
          sudo mkdir -p /opt/src/vtk
          sudo git clone --recursive --branch v${{ matrix.vtk_version }} https://gitlab.kitware.com/vtk/vtk.git /opt/src/vtk

          sudo mkdir -p ${VTK_DIR}
          cd ${VTK_DIR}
          sudo cmake \
            -DCMAKE_BUILD_TYPE:STRING=Release \
            -DBUILD_TESTING:BOOL=OFF \
            -DVTK_OPENGL_HAS_OSMESA:BOOL=OFF \
            -DVTK_DEFAULT_RENDER_WINDOW_OFFSCREEN:BOOL=OFF \
            -DVTK_USE_X:BOOL=OFF \
            -DVTK_USE_COCOA:BOOL=ON \
            -DVTK_USE_SDL2:BOOL=OFF \
            -DVTK_Group_Rendering:BOOL=OFF \
            -DBUILD_SHARED_LIBS:BOOL=ON \
            -S /opt/src/vtk -B ${VTK_DIR}
          sudo cmake --build ${VTK_DIR} -j$(sysctl -n hw.logicalcpu)

      - name: Build VT-TV
        run: |
          cd ${{ github.workspace }}
          sudo chmod +x ./ci/build.sh
          sudo mkdir -p /opt/build/vt-tv
          sudo VT_TV_COVERAGE_ENABLED=OFF ./ci/build.sh

      - name: Test
        run: |
          cd ${{ github.workspace }}
          sudo mkdir -p /opt/build/vt-tv
          sudo VT_TV_BUILD=OFF VT_TV_RUN_TESTS=ON ./ci/build.sh

        
