name: Build Documentation

on:
  push:
    branches:
      - 112-add-documentation

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git doxygen

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jinja2
          pip install pygments

      - name: Generate documentation
        id: run_doxygen
        run: |
          ./build-docs.sh ${{ secrets.GH_PAT }}
