name: Build bindings and publish to PyPI

on:
  push:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Build wheels
      run: |
        pip install cibuildwheel
        cibuildwheel --output-dir wheelhouse

    - name: Install twine
      run: |
        pip install twine

    # - name: Test wheels
    #   run: |
    #     pip install wheelhouse/*.whl
    #     # Run tests

    - name: Publish to TestPyPI
      if: github.event_name == 'push'
      run: |
        twine upload testpypi wheelhouse/*.whl
