name: Build and push Docker Image to dockerhub

on:
  pull_request:
    types: [opened, reopened, synchronize, converted_to_draft, ready_for_review]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker Build & Push
        uses: jerray/publish-docker-action@master
        with:
          # Name of the Docker image
          repository: pierrpebay/vt-tv
          # Target Docker registry
          registry: docker.io
          # dockerfile to publish
          dockerfile:
            ci/make-base-ubuntu22.04-gcc11-x64.dockerfile
          auto_tag: true
          # Docker registry username
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          # Docker registry password
          password: ${{ secrets.DOCKERHUB_TOKEN }}
