name: Docker Image CI

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker Build & Push
        uses: jerray/publish-docker-action@master
        with:
          # Name of the Docker image
          repository: pierrpebay/vt-tv
          # Target Docker registry
          registry: docker.io
          auto_tag: true
          # Docker registry username
          username: ${{ secrets.DOCKER_USERNAME }}
          # Docker registry password
          password: ${{ secrets.DOCKER_PASSWORD }}
