#WIP
name: Build dependencies and push base Docker Image to dockerhub (configure)

on:
  workflow_dispatch:
    inputs:
      # TODO(security): limit configurations as a list instead of multiple inputs
      # CONFIGURATION:
      #   type: choice
      #   description: The configuration to push
      #   options: 
      #     - ubuntu22.04-gcc11-vtk9.2.2
      BASE_IMAGE:
        default: "ubuntu:22.04"
      CC:
        default: gcc-11
      CXX:
        default: g++-11
      PYTHON:
        description: The python version to use in the inner 'deves' conda environment
        default: "3.8"
      VTK_TAG:
        description: The VTK tag to build
        default: "v9.2.2"
      IMAGE_NAME:
        description: The docker image name
        default: "ubuntu22.04-gcc11-vtk9.2.2"
      IMAGE_TAG:
        description: The docker image tag
        default: latest

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: BASE=${{ inputs.BASE_IMAGE }},VTK_TAG=${{ inputs.VTK_TAG }}
          file: ci/docker/make-base.dockerfile
          push: true
          tags: pierrpebay/${{ inputs.IMAGE_NAME }}:${{ inputs.IMAGE_TAG }}

